#!/usr/bin/env bash

#function removeAccents() {
    #cat index.html | recode -f utf8..flat > ../docs/index.html
#}

function addDTokens() {
    node scripts/getNewTokens.js

    preloads=""
    options=""
    sort -u gen/dTokens.txt > gen/dTokens2.txt
    mv gen/dTokens2.txt gen/dTokens.txt
    while read -r dToken
    do
        preloads+="<link href=\"img/"$dToken".svg\" rel=\"prefetch\" type=\"image/svg+xml\" as=\"image\"> "
        if [ "$dToken" != "dBCH" ] && [ "$dToken" != "dBTC" ] && [ "$dToken" != "dDOGE" ] && [ "$dToken" != "dETH" ] && \
           [ "$dToken" != "dFI" ] && [ "$dToken" != "dLTC" ] && [ "$dToken" != "DUSD" ]
        then
            options+="<option value=\""$dToken"\" class=\"optInvisible\">"$dToken"</option> "
        fi
    done < gen/dTokens.txt
    sed -i "s|type=\"image/svg+xml\">|type=\"image/svg+xml\"> $preloads|" ../docs/index.html
    sed -i "s|^.*dNONE.*$|$options|" ../docs/index.html
}

function addCSUM() {
    extension="$1"

    grep -o -P -e "\".*\.$extension.*?\"" index.html | while read -r line
    do
        if [[ $line == *"http"* ]]
        then
            continue
        fi

        line=${line:1:-1}
        cleanLine="${line%\?*}"
        xxcsum=`xxh32sum "$cleanLine"`
        csum="${xxcsum:0:8}"
        sed -i "s|\"$line\"|\"$cleanLine?c=$csum\"|" index.html
    done
}

function cleanPaths() {
    sed -i "s|../docs/||" "$1"
}

function minifyCSS() {
    cat css/{chart,header,info,investment,outcome,select2,style,tooltips}.css |
    sed "s|../docs/||" | sed "s|KEYS;|SUB;|" | npx postcss -m --output ../docs/css/style.min.css
    cat css/guide.css |
    sed "s|../docs/||" | npx postcss -m --output ../docs/css/guide.min.css
    cat css/queries.css |
    sed "s|../docs/||" | npx postcss -m --output ../docs/css/queries.min.css
    # Next one returns nothing by postcss somehow
    fonts=`cat css/fonts.css | sed "s|../../docs/||" | head -n9 | npx clean-css-cli -O2`
    for f in {chart,header,info,investment,outcome,select2,tooltips}.css
    do
        sed -i "/^.*$f.*$/d" ../docs/index.html
    done
    sed -i "s|^.*fonts.css.*$|<style type=\"text/css\">$fonts</style>|" ../docs/index.html
    sed -i "s|style.css|style.min.css|" ../docs/index.html
    sed -i "s|guide.css|guide.min.css|" ../docs/index.html
    sed -i "s|queries.css|queries.min.css|" ../docs/index.html
}

function minifyJS() {
    cat js/{de,en,fr,events,functions}.js | recode -f utf8..flat |
    sed "s|../docs/||" | sed "s|guide.css|guide.min.css|" |\
    npx uglifyjs -o ../docs/js/functions.min.js \
    -c -m --source-map "root='../src/js',url='functions.min.js.map'"
    sed -i "s|functions.js|functions.min.js|" ../docs/index.html
    for f in {de,en,fr,events}
    do
        sed -i "/^.*$f\.js.*$/d" ../docs/index.html
    done
}

function minifyHTML() {
    #
    #--remove-attribute-quotes
    #--minify-urls
    npx html-minifier --collapse-boolean-attributes --collapse-inline-tag-whitespace \
    --collapse-whitespace --conservative-collapse --decode-entities \
    --no-include-auto-generated-tags --prevent-attributes-escaping \
    --process-conditional-comments --remove-comments --remove-empty-attributes \
    --remove-redundant-attributes --sort-attributes --sort-class-name \
    --trim-custom-fragments --use-short-doctype ../docs/index.html  -o ../docs/index.html
}

cp -a index.html ../docs/index.html
#removeAccents
addDTokens
minifyCSS
minifyJS
cd ../docs
cleanPaths index.html
addCSUM js
addCSUM css
cd ../src
minifyHTML
