#!/usr/bin/env bash


function addCSUM() {
    extension="$1"

    grep -o -P -e "\".*\.$extension.*?\"" index.html | while read -r line
    do
        if [[ $line == *"http"* ]]
        then
            continue
        fi

        line=${line:1:-1}
        cleanLine="${line%\?*}"
        xxcsum=`xxh32sum "$cleanLine"`
        csum="${xxcsum:0:8}"
        sed -i "s|\"$line\"|\"$cleanLine?c=$csum\"|" index.html
    done
}

function cleanPaths() {
    sed -i "s|../docs/||" index.html
}

function concatFiles() {
    cat css/{chart,fonts,guide,select2,style}.css | npx postcss -m  > ../docs/css/style.min.css
    sed -i "s/style.css/style.min.css/" ../docs/index.html
    for f in {chart,fonts,guide,select2}.css
    do
        sed -i "/^.*$f.*$/d" ../docs/index.html
    done

    uglifyjs js/{events,functions}.js -o ../docs/js/functions.min.js \
    -c -m --source-map "root='../src/js',url='functions.min.js.map'"
    sed -i "s/functions.js/functions.min.js/" ../docs/index.html
    for f in events.js
    do
        sed -i "/^.*$f.*$/d" ../docs/index.html
    done
}

cp -a index.html ../docs/
concatFiles
cd ../docs/
cleanPaths
addCSUM js
addCSUM css
