const en = {
    header: {
    },
    investment: {
        inv: "Investment",
        IP: "Initial Prices",
        FP: "Final Prices",
        IA: "Initial Amounts",
        int: "Interest",
        APR: "APR",
        fee: "Comm.",
        time: "Time",
        comp: "Comp.",
        tax: "Tax"
    },
    outcome: {
        out: "Outcome",
        LMA: "Liquidity Mining Amounts",
        WOINT: "W/o Interest",
        WINT: "With Interest",
        values: "Values",
        init: "Initial",
        hold: "Holding",
        hold1: "Holding One",
        holdD: "Holding ",
        holdT: "Holding ",
        LMWOI: "LM w/o Int.",
        LMWI: "LM with Int."
    },
    plot: {
        title: "Changes in LM/Holding total value due to prices variations",
        y: "LM/Holding total value, in %.",
        x1: "Final/Initial price of ",
        x2: " in ",
        x3: ", in %.",
        lint: "&#9632;with interest",
        lnint: "&#9632;w/o interest"
    },
    tour: {
        play: "Welcome to the tutorial! This button replays it.",
        infoB: "This button toggles the information tab.",
        urlB: "This button opens the site on a new tab with the current values of the calculator.",
        title: "This calculator estimates potential divergent changes.",
        CurrencyValueDiv: "Select the currency.",
        FirstTokenValueDiv: "Select the first coin in the pool.",
        OtherTokenValueDiv: "Select the other coin.",
        sync: "Get prices from CoinGecko.",
        cPriceFirstTokenDiv: "Enter the first coins's initial price.",
        cPriceOtherTokenDiv: "Enter the other coin's initial price.",
        cPriceRatioDiv: "Gives the other coin's initial price in DFI.",
        fPriceFirstTokenDiv: "Enter the first coins's final price.",
        fPriceOtherTokenDiv: "Enter the other coin's final price.",
        cAmountFirstTokenDiv: "Enter the amount of DFI provided to the pool.",
        cAmountOtherTokenDiv: "The other coin's provided amount is automatically calculated.",
        interestH: "This section is optional.",
        aprDiv: "Enter the pool's rewards in APR.",
        feeDiv: "Enter the pool's commissions in APR.",
        durationDiv: "Enter days in liquidity mining.",
        periodDiv: "Enter period in days to compound, the minimum is 0.0003472, apart from 0 which means no compounding.",
        taxDiv: "Enter tax rate.",
        LMA: "Amounts of coins after liquidity mining",
        IV: "Based on initial prices and amounts.",
        HV: "Based on initial amounts and final prices.",
        HV1: "Only holding one of the two.",
        LMV: "Based on final amounts and prices, without interest.",
        LMIV: "Based on final amounts and prices, with interest.",
        plot: "This plots potential values, based on the other coin's final price in DFI."
    },
    info: {
        welcome: "Welcome to DeFiChain Tools!",
        welcome2: "This site currently only offers a Liquidity Mining Calculator, but more will be added soon.",
        links: "This site is accessible on the web at <a href=\"https://www.defichain.tools\">https://www.defichain.tools</a>",
        ipfs: "It is also available on IPFS at <a href=\"/ipns/defichain.tools/\">/ipns/defichain.tools/</a>",
        gh: "You can find the source to this site and file feature requests/bugs at <a href=\"https://github.com/John-Gee/DFC_LM/\">https://github.com/John-Gee/DFC_LM/</a>",
        email_off: "You can also contact us at <a href=\"mailto:contact@defichain.tools?subject=DefiChainTools\"> contact@defichain.tools</a>",
        donation: "If you appreciate this site and want to support it, you can donate to this DeFiChain address:"
    }
};
