const fr = {
    header: {
    },
    investment: {
        inv: "Investissement",
        IP: "Prix Initiaux",
        FP: "Prix Finaux",
        IA: "Montants Initiaux",
        int: "Intérêts",
        APR: "TA",
        fee: "Comm.",
        time: "Temps",
        comp: "Comp.",
        tax: "Taxe"
    },
    outcome: {
        out: "Resultat",
        LMA: "Montants De Minage De Liquidite",
        WOINT: "Sans Intérêts",
        WINT: "Avec Intérêts",
        values: "Valeurs",
        init: "Initiales",
        hold: "Gardees",
        hold1: "Gardees d'un",
        holdD: "Gardees de ",
        holdT: "Gardees de ",
        LMWOI: "MDL Sans Intérêts",
        LMWI: "MDL Avec Intérêts"
    },
    plot: {
        title: "Changements des valeurs totales MDL/Gardées dues aux variations de prix",
        y: "Valeurs totales MDL/Gardées, en %.",
        x1: "Prix final/initial de ",
        x2: " en ",
        x3: ", en %.",
        lint: "&#9632;Avec Intérêts",
        lnint: "&#9632;Sans Intérêts"
    },
    tour: {
        play: "Bienvenue au tutoriel! Ce bouton le relance.",
        infoB: "Ce bouton bascule l'onglet d'information.",
        urlB: "Ce bouton ouvre le site sur un nouvel onglet avec les valeurs actuelles du calculateur.",
        title: "Ce calculateur estime des changements divergents potentiels.",
        CurrencyValueDiv: "Choisissez la devise.",
        FirstTokenValueDiv: "Choisissez la 1ère monnaie dans la paire.",
        OtherTokenValueDiv: "Choisissez l'autre monnaie.",
        sync: "Récupérez les prix depuis CoinGecko.",
        cPriceFirstTokenDiv: "Entrez le prix initial de la première monnaie.",
        cPriceOtherTokenDiv: "Entrez le prix initial de l'autre monnaie.",
        cPriceRatioDiv: "Donne le prix initial de l'autre monnaie en DFI.",
        fPriceFirstTokenDiv: "Entrer le prix final de la première monnaie.",
        fPriceOtherTokenDiv: "Entrer le prix final de l'autre monnaie.",
        cAmountFirstTokenDiv: "Entrer le montant de DFI fournit au fond.",
        cAmountOtherTokenDiv: "Le montant de l'autre monnaie fournit est calculé automatiquement.",
        interestH: "Cette section est optionelle.",
        aprDiv: "Entrez le taux annuel d'intérêt du fond.",
        feeDiv: "Entrez le taux annuel de commissions du fond.",
        durationDiv: "Entrez le nombre de jour du placement dans le fond.",
        periodDiv: "Entrez la fréquence en jour de composition des intérêts, le minimum est 0.0003472, mis à part 0 qui veut dire pas de composition.",
        taxDiv: "Entrez le taux de taxe.",
        LMA: "Montant de monnaies après minage de liquidité.",
        IV: "Basés sur les prix et montants initiaux.",
        HV: "Basés sur les montants initiaux et prix finaux.",
        HV1: "En ne gardant qu'un des deux.",
        LMV: "Basés sur les montants et prix finaux, sans intérêt.",
        LMIV: "Basés sur les montants et prix finaux, avec intérêt.",
        plot: "Ceci trace les valeurs potentielles, selon le changement de valeur de l'autre monnaie en DFI."
    },
    info: {
        welcome: "Bienvenue sur DeFiChain Tools!",
        welcome2: "Ce site n'offre qu'un calculateur pour Minage de Liquidité, mais d'autres outils seront bientôt ajoutés.",
        links: "Ce site est accessible sur le web à <a href=\"https://www.defichain.tools\">https://www.defichain.tools</a>",
        ipfs: "Il est aussi accessible sur IPFS à <a href=\"IPFS://ipns/defichain.tools/\">IPFS://ipns/defichain.tools/</a>",
        gh: "Vous pouvez trouver les sources de ce site et remplir des requêtes de fonctionnalités/rapports de bogues sur <a href=\"https://github.com/John-Gee/DFC_LM/\">https://github.com/John-Gee/DFC_LM/</a>",
        email_off: "Vous pouvez aussi nous contacter à <a href=\"mailto:contact@defichain.tools?subject=DefiChainTools\" contact@defichain.tools</a>",
        donation: "Si vous appréciez ce site et souhaitez le supporter, vous pouvez faire une donation sur cette adresse DeFiChain :"
    }
}
